/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EncryptedSoilMoistureInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getEncryptedSoilMoisture"
      | "getLastUpdateTimestamp"
      | "hasInitialized"
      | "protocolId"
      | "recordSoilMoisture"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "SoilMoistureRecorded" | "SoilMoistureUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getEncryptedSoilMoisture",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLastUpdateTimestamp",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasInitialized",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordSoilMoisture",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getEncryptedSoilMoisture",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastUpdateTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordSoilMoisture",
    data: BytesLike
  ): Result;
}

export namespace SoilMoistureRecordedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SoilMoistureUpdatedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EncryptedSoilMoisture extends BaseContract {
  connect(runner?: ContractRunner | null): EncryptedSoilMoisture;
  waitForDeployment(): Promise<this>;

  interface: EncryptedSoilMoistureInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getEncryptedSoilMoisture: TypedContractMethod<
    [user: AddressLike],
    [string],
    "view"
  >;

  getLastUpdateTimestamp: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  hasInitialized: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  recordSoilMoisture: TypedContractMethod<
    [encryptedMoisture: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getEncryptedSoilMoisture"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getLastUpdateTimestamp"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasInitialized"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "recordSoilMoisture"
  ): TypedContractMethod<
    [encryptedMoisture: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "SoilMoistureRecorded"
  ): TypedContractEvent<
    SoilMoistureRecordedEvent.InputTuple,
    SoilMoistureRecordedEvent.OutputTuple,
    SoilMoistureRecordedEvent.OutputObject
  >;
  getEvent(
    key: "SoilMoistureUpdated"
  ): TypedContractEvent<
    SoilMoistureUpdatedEvent.InputTuple,
    SoilMoistureUpdatedEvent.OutputTuple,
    SoilMoistureUpdatedEvent.OutputObject
  >;

  filters: {
    "SoilMoistureRecorded(address,uint256)": TypedContractEvent<
      SoilMoistureRecordedEvent.InputTuple,
      SoilMoistureRecordedEvent.OutputTuple,
      SoilMoistureRecordedEvent.OutputObject
    >;
    SoilMoistureRecorded: TypedContractEvent<
      SoilMoistureRecordedEvent.InputTuple,
      SoilMoistureRecordedEvent.OutputTuple,
      SoilMoistureRecordedEvent.OutputObject
    >;

    "SoilMoistureUpdated(address,uint256)": TypedContractEvent<
      SoilMoistureUpdatedEvent.InputTuple,
      SoilMoistureUpdatedEvent.OutputTuple,
      SoilMoistureUpdatedEvent.OutputObject
    >;
    SoilMoistureUpdated: TypedContractEvent<
      SoilMoistureUpdatedEvent.InputTuple,
      SoilMoistureUpdatedEvent.OutputTuple,
      SoilMoistureUpdatedEvent.OutputObject
    >;
  };
}
